#!/usr/bin/env bash
# Make a fresh worktree runnable: seed gitignored dev files from the main checkout,
# allocate ports, isolate its DB settings, write Claude Code's sandbox settings,
# install deps + git hooks, and open its tmux dev session.
# Idempotent on purpose: wt runs it from post_create AND post_checkout (some wt
# builds fire both on create), and you can re-run it by hand to refresh.
#   scripts/wt-setup.sh          from inside a worktree
#   (wt hooks call it with WT_PATH / WT_BRANCH exported)
set -euo pipefail
ROOT="${WT_PATH:-$(git rev-parse --show-toplevel)}"
SCRIPTS="$(dirname "$(readlink -f "$0")")"
. "$SCRIPTS/wt-lib.sh"
MAIN="$(main_checkout)"   # not $WT_MAIN: wt points that at whichever worktree holds `dev`
BRANCH="${WT_BRANCH:-$(current_branch)}"
cd "$ROOT"
[ "$ROOT" != "$MAIN" ] || die "run from a worktree, not the main checkout"
# Prefer the branch's own copy of the tooling; fall back to the main checkout's for
# branches that predate it.
tooling() { [ -f "$ROOT/scripts/$1" ] && echo "$ROOT/scripts/$1" || echo "$MAIN/scripts/$1"; }

echo "==> worktree $ROOT ($BRANCH)"

# 1. Gitignored dev files aren't in the branch; the main checkout's copies on disk
#    are the right source whatever it has checked out. Never overwrite.
for f in secrets/.env docker-compose.override.yml frontend/.env.development.local; do
  if [ ! -e "$f" ] && [ -e "$MAIN/$f" ]; then
    mkdir -p "$(dirname "$f")"; cp "$MAIN/$f" "$f"; echo "seeded $f"
  fi
done
[ -f secrets/.env ] || die "no secrets/.env in $MAIN to seed from — create it first (README > Secrets)"

# 1b. Sample contribution batches. The CSVs are generated and untracked
#     (sample-data/.gitignore), but fieldGroups.spec.ts reads their headers and
#     the contribution flow wants drop-in test data, so a worktree without them
#     starts broken. Copy only the generated batch folders: the top-level files
#     (generate.py, README.md) are tracked and belong to the branch.
if ! find sample-data -name '*.csv' -print -quit 2>/dev/null | grep -q .; then
  found=""
  for d in "$MAIN"/sample-data/*/; do
    if [ -d "$d" ]; then cp -r "$d" sample-data/; found=yes; fi
  done
  if [ -n "$found" ]; then
    echo "seeded sample-data/ from $MAIN"
  else
    echo "note: no generated sample-data in $MAIN; run 'make sample-data' (here or there) if you need it"
  fi
fi

# 2. Ports and names. A previous run may have cloned a branch DB: keep it.
branch_ports "$BRANCH"
SLUG="$(slug "$BRANCH")"
prev_db=""; [ -f .env.worktree ] && prev_db="$(sed -n 's/^DB_NAME=//p' .env.worktree)"
DB_NAME="${prev_db:-$SHARED_DB}"
DATA_DIR="$(readlink -f "$MAIN/../resslab-hub-data" 2>/dev/null || echo "$MAIN/../resslab-hub-data")"
cat > .env.worktree <<ENV
# Generated by scripts/wt-setup.sh — this worktree's private settings (gitignored).
# tmux-dev.sh exports these in every window; re-run wt-setup.sh to refresh.
WT_BRANCH=$BRANCH
WT_SLUG=$SLUG
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
DB_NAME=$DB_NAME
POSTGRES_TEST_DB=resslab_hub_test_$SLUG
RESSLAB_DATA_DIR=$DATA_DIR
ENV
echo "ports: backend $BACKEND_PORT, frontend $FRONTEND_PORT; database: $DB_NAME"

# 3. This frontend talks to this backend; this backend talks to the right DB and
#    never migrates the shared one (wt-db.sh create flips DATABASE_UPGRADE on).
set_env_var frontend/.env.development.local VITE_APP_BACKEND_URL "http://127.0.0.1:$BACKEND_PORT"
set_env_var secrets/.env POSTGRES_DB "$DB_NAME"
set_env_var secrets/.env POSTGRES_TEST_DB "resslab_hub_test_$SLUG"
if [ "$DB_NAME" = "$SHARED_DB" ]; then set_env_var secrets/.env DATABASE_UPGRADE false
else set_env_var secrets/.env DATABASE_UPGRADE true; fi

# 3b. Own throwaway database: clone the ~20 MB light template (sub-second) so
#     this worktree can migrate, upload, or break its DB without touching the
#     shared dataset. Best-effort: without the container or a template we stay
#     on the shared DB and say so; `make db-branch` retries later.
if [ "$DB_NAME" = "$SHARED_DB" ]; then
  if ROOT="$ROOT" "$(tooling wt-db.sh)" create; then :
  else echo "note: staying on the shared $SHARED_DB — build the light template once with 'make db-template-light', then run 'make db-branch' here"
  fi
fi

# 4. Claude Code runs sandboxed here with the ask/deny rules from the template.
#    .claude/ is gitignored, so the worktree's copy never reaches a commit.
mkdir -p .claude
sed "s|__RESSLAB_DATA_DIR__|$DATA_DIR|g" "$(tooling claude-worktree-settings.json)" > .claude/settings.local.json
echo "wrote .claude/settings.local.json"

# 5. Dependencies (skipped when already present) and lefthook, which refuses
#    commits from a checkout where it isn't installed.
if [ ! -d node_modules ] || [ ! -d frontend/node_modules ] || [ ! -d backend/.venv ]; then make install; fi
make hooks

# 6. Detached tmux session "<repo>/<branch>"; switch to it with prefix+s.
ROOT="$ROOT" "$(tooling tmux-dev.sh)" --no-attach   # ROOT: the script may be the main checkout's copy
