#!/usr/bin/env bash
# Make a fresh worktree runnable: repair the branch's tracking, link the big
# gitignored dev data from the main checkout, allocate ports, write Claude Code's
# sandbox settings, install deps and the push guard, and open its tmux dev session.
# Idempotent on purpose: wt runs it from post_create AND post_checkout (some wt
# builds fire both on create), and you can re-run it by hand to refresh.
#   scripts/wt-setup.sh          from inside a worktree
#   (wt hooks call it with WT_PATH / WT_BRANCH exported)
set -euo pipefail
ROOT="${WT_PATH:-$(git rev-parse --show-toplevel)}"
SCRIPTS="$(dirname "$(readlink -f "$0")")"
. "$SCRIPTS/wt-lib.sh"
MAIN="$(main_checkout)"   # not $WT_MAIN: wt points that at whichever worktree holds `dev`
BRANCH="${WT_BRANCH:-$(current_branch)}"
cd "$ROOT"
[ "$ROOT" != "$MAIN" ] || die "run from a worktree, not the main checkout"
# Prefer the branch's own copy of the tooling; fall back to the main checkout's for
# branches that predate it.
tooling() { [ -f "$ROOT/scripts/$1" ] && echo "$ROOT/scripts/$1" || echo "$MAIN/scripts/$1"; }

echo "==> worktree $ROOT ($BRANCH)"

# 0. Tracking. `wt create <branch> origin/dev` cuts the branch from a
#    remote-tracking ref, and git's default autoSetupMerge then points the new
#    branch's upstream at origin/dev. `git pull` there rebases the branch onto
#    dev instead of fetching its own commits, the next push is refused as
#    non-fast-forward, and `git pull` still answers "up to date" because it is
#    comparing against dev. That happened in resslab-hub and left a HEAD
#    detached. `simple` only tracks a remote branch of the same name, and
#    push.autoSetupRemote sets the upstream on the first push, so a new branch
#    gets the right one or none at all. Repo-wide config, but written here so
#    every checkout of this repo gets it.
git config branch.autoSetupMerge simple || echo "note: could not set branch.autoSetupMerge"
git config push.autoSetupRemote true || echo "note: could not set push.autoSetupRemote"
if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH"; then
  git branch --set-upstream-to="origin/$BRANCH" "$BRANCH" >/dev/null 2>&1 ||
    echo "note: could not track origin/$BRANCH"
elif [ "$(git config --get "branch.$BRANCH.merge" || true)" != "refs/heads/$BRANCH" ]; then
  # Not pushed yet: no upstream at all beats one pointing at another branch.
  git branch --unset-upstream "$BRANCH" >/dev/null 2>&1 || true
fi

# 1. Gitignored dev data isn't in the branch, and it is big (~100 MB of PMTiles),
#    so link it instead of copying. Vite and FastAPI both follow symlinks, and a
#    worktree that shares the tiles cannot drift from the main checkout.
#    Best effort: a missing source only prints a note, nothing here is required
#    to boot the servers.
link_from_main() {
  local rel=$1
  [ -e "$ROOT/$rel" ] && return 0            # already there (real dir or link)
  [ -e "$MAIN/$rel" ] || { echo "note: no $rel in $MAIN, skipped"; return 0; }
  mkdir -p "$(dirname "$ROOT/$rel")"
  ln -s "$MAIN/$rel" "$ROOT/$rel"
  echo "linked $rel -> $MAIN/$rel"
}
link_from_main frontend/public/geodata          # PMTiles served at /geodata in dev
# The CVRP centroid CSVs are untracked; the graphml/geojson next to them are
# tracked, so git already brought those.
for csv in "$MAIN"/backend/data/*.csv; do
  [ -e "$csv" ] || continue
  link_from_main "backend/data/$(basename "$csv")"
done
link_from_main backend/.env                     # optional, config.py has defaults

# 2. Ports and names. A previous run may have picked ports (the servers in the
#    session listen on them, and the hash input has changed once already): keep
#    them. A fresh worktree gets the hashed pair, or the next free one
#    (branch_ports in wt-lib.sh).
prev_backend=""; prev_frontend=""
if [ -f .env.worktree ]; then
  prev_backend="$(sed -n 's/^BACKEND_PORT=//p' .env.worktree)"
  prev_frontend="$(sed -n 's/^FRONTEND_PORT=//p' .env.worktree)"
fi
if [ -n "$prev_backend" ] && [ -n "$prev_frontend" ]; then
  BACKEND_PORT="$prev_backend"; FRONTEND_PORT="$prev_frontend"
else
  branch_ports "$BRANCH"
fi
SLUG="$(slug "$BRANCH")"
cat > .env.worktree <<ENV
# Generated by scripts/wt-setup.sh — this worktree's private settings (gitignored).
# tmux-dev.sh exports these in every window; re-run wt-setup.sh to refresh.
WT_BRANCH=$BRANCH
WT_SLUG=$SLUG
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
ENV
echo "ports: backend $BACKEND_PORT, frontend $FRONTEND_PORT"

# 3. Nothing else to wire: vite.config.ts runs in Node and reads BACKEND_PORT /
#    FRONTEND_PORT from the environment, and the frontend reaches the backend
#    through vite's own /api proxy. No env file to write.

# 4. Claude Code runs sandboxed here with the ask/deny rules from the template.
#    .claude/settings.local.json is gitignored, so it never reaches a commit.
#    Always read the template from the main checkout, not the branch: a branch
#    forked before a template fix would otherwise write the old rules back (that
#    is how two worktrees got the `python3 -` ask rule after it was removed),
#    and a feature branch should not be able to change Claude's permissions.
#    Not fatal: a re-run from inside a sandboxed agent cannot write this file
#    (Claude blocks an agent editing its own permissions), and in that case the
#    file is already there. Copied to a temp file first so a refused write
#    cannot leave a truncated one behind.
mkdir -p .claude
if cp "$MAIN/scripts/claude-worktree-settings.json" .claude/settings.local.json.tmp 2>/dev/null &&
   mv .claude/settings.local.json.tmp .claude/settings.local.json 2>/dev/null; then
  echo "wrote .claude/settings.local.json"
else
  rm -f .claude/settings.local.json.tmp
  echo "note: could not write .claude/settings.local.json (kept the existing one; re-run wt-setup.sh from a terminal to refresh it)"
fi

# 5. Dependencies (skipped when already present). processing/ is left out on
#    purpose: it is a third uv project, rarely touched on a feature branch, and
#    each worktree already carries node_modules plus a backend venv. Run
#    `cd processing && uv sync` by hand in a worktree that needs it.
[ -d frontend/node_modules ] || (cd frontend && pnpm install --frozen-lockfile)
[ -d backend/.venv ] || (cd backend && uv sync)

# 6. The push guard, as a plain pre-push hook. Worktrees share the common hooks
#    directory with the main checkout, so this installs it once for everyone; the
#    guard exits early when it runs in the main checkout. The hook prefers the
#    pushing checkout's own copy of the guard and falls back to the main
#    checkout's, so a branch cut before this tooling existed is still guarded.
#    A pre-push hook that was already there (git-lfs installs one) is kept and
#    still runs after the guard, with the same refs on its stdin.
HOOK_MARK="# wt push guard"
# core.hooksPath wins over .git/hooks when it is set (husky sets it), so follow
# it: a guard installed in the directory git ignores would never run.
hooks_path="$(git config --get core.hooksPath || true)"
if [ -n "$hooks_path" ]; then
  case "$hooks_path" in /*) hooks_dir="$hooks_path";; *) hooks_dir="$MAIN/$hooks_path";; esac
else
  hooks_dir="$(git rev-parse --path-format=absolute --git-common-dir)/hooks"
fi
mkdir -p "$hooks_dir"
if [ -f "$hooks_dir/pre-push" ] && ! grep -qF "$HOOK_MARK" "$hooks_dir/pre-push"; then
  mv "$hooks_dir/pre-push" "$hooks_dir/pre-push.before-wt"
  echo "kept the existing pre-push hook as pre-push.before-wt, it still runs"
fi
cat > "$hooks_dir/pre-push" <<HOOK
#!/bin/sh
$HOOK_MARK — installed by scripts/wt-setup.sh, shared by every checkout of this repo.
# git feeds the refs it is about to push on stdin, and both consumers need them,
# so read them once and hand a copy to each.
refs=\$(cat)
guard="\$(git rev-parse --show-toplevel)/scripts/git-push-guard.sh"
[ -f "\$guard" ] || guard="\$(dirname "\$(git rev-parse --path-format=absolute --git-common-dir)")/scripts/git-push-guard.sh"
[ -f "\$guard" ] || { echo "push-guard: scripts/git-push-guard.sh not found, refusing to push unguarded" >&2; exit 1; }
printf '%s\n' "\$refs" | bash "\$guard" "\$@" || exit 1
prev="\$(dirname "\$0")/pre-push.before-wt"
[ -x "\$prev" ] || exit 0
printf '%s\n' "\$refs" | "\$prev" "\$@"
HOOK
chmod +x "$hooks_dir/pre-push"
echo "installed pre-push guard in $hooks_dir"

# 7. Detached tmux session "<repo>/<branch>"; switch to it with prefix+s.
ROOT="$ROOT" "$(tooling tmux-dev.sh)" --no-attach   # ROOT: the script may be the main checkout's copy
