#!/usr/bin/env bash
# Make a fresh worktree runnable: link the big gitignored dev data from the main
# checkout, allocate ports, write Claude Code's sandbox settings, install deps and
# the push guard, and open its tmux dev session.
# Idempotent on purpose: wt runs it from post_create AND post_checkout (some wt
# builds fire both on create), and you can re-run it by hand to refresh.
#   scripts/wt-setup.sh          from inside a worktree
#   (wt hooks call it with WT_PATH / WT_BRANCH exported)
set -euo pipefail
ROOT="${WT_PATH:-$(git rev-parse --show-toplevel)}"
SCRIPTS="$(dirname "$(readlink -f "$0")")"
. "$SCRIPTS/wt-lib.sh"
MAIN="$(main_checkout)"   # not $WT_MAIN: wt points that at whichever worktree holds `dev`
BRANCH="${WT_BRANCH:-$(current_branch)}"
cd "$ROOT"
[ "$ROOT" != "$MAIN" ] || die "run from a worktree, not the main checkout"
# Prefer the branch's own copy of the tooling; fall back to the main checkout's for
# branches that predate it.
tooling() { [ -f "$ROOT/scripts/$1" ] && echo "$ROOT/scripts/$1" || echo "$MAIN/scripts/$1"; }

echo "==> worktree $ROOT ($BRANCH)"

# 1. Gitignored dev data isn't in the branch, and it is big (~100 MB of PMTiles),
#    so link it instead of copying. Vite and FastAPI both follow symlinks, and a
#    worktree that shares the tiles cannot drift from the main checkout.
#    Best effort: a missing source only prints a note, nothing here is required
#    to boot the servers.
link_from_main() {
  local rel=$1
  [ -e "$ROOT/$rel" ] && return 0            # already there (real dir or link)
  [ -e "$MAIN/$rel" ] || { echo "note: no $rel in $MAIN, skipped"; return 0; }
  mkdir -p "$(dirname "$ROOT/$rel")"
  ln -s "$MAIN/$rel" "$ROOT/$rel"
  echo "linked $rel -> $MAIN/$rel"
}
link_from_main frontend/public/geodata          # PMTiles served at /geodata in dev
# The CVRP centroid CSVs are untracked; the graphml/geojson next to them are
# tracked, so git already brought those.
for csv in "$MAIN"/backend/data/*.csv; do
  [ -e "$csv" ] || continue
  link_from_main "backend/data/$(basename "$csv")"
done
link_from_main backend/.env                     # optional, config.py has defaults

# 2. Ports and names.
branch_ports "$BRANCH"
SLUG="$(slug "$BRANCH")"
cat > .env.worktree <<ENV
# Generated by scripts/wt-setup.sh — this worktree's private settings (gitignored).
# tmux-dev.sh exports these in every window; re-run wt-setup.sh to refresh.
WT_BRANCH=$BRANCH
WT_SLUG=$SLUG
BACKEND_PORT=$BACKEND_PORT
FRONTEND_PORT=$FRONTEND_PORT
ENV
echo "ports: backend $BACKEND_PORT, frontend $FRONTEND_PORT"

# 3. Nothing else to wire: vite.config.ts runs in Node and reads BACKEND_PORT /
#    FRONTEND_PORT from the environment, and the frontend reaches the backend
#    through vite's own /api proxy. No env file to write.

# 4. Claude Code runs sandboxed here with the ask/deny rules from the template.
#    .claude/settings.local.json is gitignored, so it never reaches a commit.
#    Not fatal: a re-run from inside a sandboxed agent cannot write this file
#    (Claude blocks an agent editing its own permissions), and the file is
#    already there in that case.
mkdir -p .claude
if cp "$(tooling claude-worktree-settings.json)" .claude/settings.local.json 2>/dev/null; then
  echo "wrote .claude/settings.local.json"
else
  echo "note: could not write .claude/settings.local.json (kept the existing one)"
fi

# 5. Dependencies (skipped when already present). processing/ is left out on
#    purpose: it is a third uv project, rarely touched on a feature branch, and
#    each worktree already carries node_modules plus a backend venv. Run
#    `cd processing && uv sync` by hand in a worktree that needs it.
[ -d frontend/node_modules ] || (cd frontend && npm install)
[ -d backend/.venv ] || (cd backend && uv sync)

# 6. The push guard, as a plain pre-push hook. Worktrees share the common hooks
#    directory with the main checkout, so this installs it once for everyone; the
#    guard exits early when it runs in the main checkout. The hook prefers the
#    pushing checkout's own copy of the guard and falls back to the main
#    checkout's, so a branch cut before this tooling existed is still guarded.
#    A pre-push hook that was already there (git-lfs installs one) is kept and
#    still runs after the guard, with the same refs on its stdin.
HOOK_MARK="# wt push guard"
# core.hooksPath wins over .git/hooks when it is set (husky sets it), so follow
# it: a guard installed in the directory git ignores would never run.
hooks_path="$(git config --get core.hooksPath || true)"
if [ -n "$hooks_path" ]; then
  case "$hooks_path" in /*) hooks_dir="$hooks_path";; *) hooks_dir="$MAIN/$hooks_path";; esac
else
  hooks_dir="$(git rev-parse --path-format=absolute --git-common-dir)/hooks"
fi
mkdir -p "$hooks_dir"
if [ -f "$hooks_dir/pre-push" ] && ! grep -qF "$HOOK_MARK" "$hooks_dir/pre-push"; then
  mv "$hooks_dir/pre-push" "$hooks_dir/pre-push.before-wt"
  echo "kept the existing pre-push hook as pre-push.before-wt, it still runs"
fi
cat > "$hooks_dir/pre-push" <<HOOK
#!/bin/sh
$HOOK_MARK — installed by scripts/wt-setup.sh, shared by every checkout of this repo.
# git feeds the refs it is about to push on stdin, and both consumers need them,
# so read them once and hand a copy to each.
refs=\$(cat)
guard="\$(git rev-parse --show-toplevel)/scripts/git-push-guard.sh"
[ -f "\$guard" ] || guard="\$(dirname "\$(git rev-parse --path-format=absolute --git-common-dir)")/scripts/git-push-guard.sh"
[ -f "\$guard" ] || { echo "push-guard: scripts/git-push-guard.sh not found, refusing to push unguarded" >&2; exit 1; }
printf '%s\n' "\$refs" | bash "\$guard" "\$@" || exit 1
prev="\$(dirname "\$0")/pre-push.before-wt"
[ -x "\$prev" ] || exit 0
printf '%s\n' "\$refs" | "\$prev" "\$@"
HOOK
chmod +x "$hooks_dir/pre-push"
echo "installed pre-push guard in $hooks_dir"

# 7. Detached tmux session "<repo>/<branch>"; switch to it with prefix+s.
ROOT="$ROOT" "$(tooling tmux-dev.sh)" --no-attach   # ROOT: the script may be the main checkout's copy
